version: '3'
services:
    lv:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-:-$(id -g)}'
        image: sail-8.2/app
        container_name: '${APP_NAME:-msvc}_lv'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER:-$(id -u)}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - redis
            - mailpit
            - selenium
    pgsql:
        image: 'postgres:15'
        container_name: '${APP_NAME:-msvc}_pgsql'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        hostname: pgsql
        environment:
            PGDATA: '/var/lib/postgresql/data/db'
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql-data:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        container_name: '${APP_NAME:-msvc}_redis'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        hostname: redis
        volumes:
            - 'redis-data:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: '${APP_NAME:-msvc}_mailpit'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        hostname: mailpit
        networks:
            - sail
    selenium:
        image: selenium/standalone-chrome
        container_name: '${APP_NAME:-msvc}_selenium'
        hostname: selenium
        shm_size: "2gb"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '/dev/shm:/dev/shm'
            - 'chrome-data:/external/chrome/data'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    pgsql-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./volumes/pgsql
    redis-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./volumes/redis
    chrome-data:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ./volumes/selenium/chrome-data
